
var thousand = [
  [4,"Male","Guilty","Marketing","Supports death penalty","None stated","Probably excused","<blockquote class='twitter-tweet' lang='en'><p>Juror 296, an older Asian man. Was a software engineer, in biotech field.</p>&mdash; Milton Valencia (@MiltonValencia) <a href='https://twitter.com/MiltonValencia/status/563067511550525440'>February 4, 2015</a></blockquote>"],
  [6,"Male","Guilty but can stay open","Real Estate","Supports but open","Wife a nurse, treated patients","Possibly kept",0],
  [7,"Male","No Determination","Deli owner","Supports but open","Wife is five months pregnant ","Not clear/Claming hardship",0],
  [9,"Male","Guilty but can stay open","Custodian","Against death penalty","None stated","Probably excused",0],
  [10,"Male","Guilty but can stay open","Professor","Against death penalty","None stated","Probably excused",0],
  [11,"Male","No Determination","Software engineer","Supports but open","None stated","Possibly kept",0],
  [14,"Male","Guilty","N/A","Supports death penalty","Could not hear/Technical difficulties","Probably excused",0],
  [15,"Female","Guilty","Makeup artist","Supports death penalty","None stated","Probably excused",0],
  [16,"Male","No Determination","Limo driver","Open","None stated","Not clear",0],
  [19,"Male","Guilty but can stay open","Software engineer","Against death penalty","Bought Boston Strong merchandise","Probably excused",0],
  [20,"Female","Guilty","Administrator","N/A","None stated","Probably excused",0],
  [21,"Male","No Determination","Software engineer","Against but open","None stated","Not clear",0],
  [22,"Male","N/A","psycotherapist","N/A","Hardship for his clients","Claiming hardship",0],
  [23,"Female","Guilty but can stay open","Administrator","Against death penalty","None stated","Probably excused",0],
  [26,"Male","N/A","Insurance appraiser","N/A","Financial difficulty","Claiming hardship",0],
  [27,"Female","No Determination","Lawyer","Against but open","None stated","Possibly kept",0],
  [28,"Female","N/A","Lawyer","N/A","Family travel plans","Claiming hardship",0],
  [30,"Male","Guilty","Store Manager","N/A","Niece's boyfriend's brother an MIT cop","Probably excused",0],
  [31,"Female","","Store ManagerND","Against death penalty","None stated","Probably excused",0],
  [32,"Male","N/A","N/A","Against but open","Medical condition","Not clear",0],
  [33,"Female","Guilty","N/A","N/A","Husband a State Police trooper","Probably excused",0],
  [35,"Male","Guilty but can stay open","Ma Department of Energy","Open","Donated to One Fund","Possibly kept",0],
  [37,"Female","N/A","N/A","N/A","Medical condition","Claiming hardship",0],
  [38,"Male","Guilty","Computer Tech","Open","Close friend a Boston police officer","Probably excused",0],
  [40,"Female","N/A","Runs non-profit education support","N/A","Lives in Dorchester, met Martin Richard","Probably excused",0],
  [41,"Female","No Determination","Executive Assistant ","Open","None stated","Possibly kept",0],
  [42,"Male","Guilty but can stay open","Criminal justice expert","Against death penalty","Ran Marathon 4 times","Probably excused",0],
  [43,"Male","No Determination","Biologist pharmaceutical industry","Against death penalty","None stated","Probably excused",0],
  [46,"Male","N/A","Sports field caretaker","N/A","Son was at Marathon finish line","Claiming hardship",0],
  [47,"Male","N/A","N/A","N/A","English not first language","Claiming hardship",0],
  [48,"Male","Guilty","Retired Truck Driver","N/A","Financial difficulty","Claiming hardship",0],
  [49,"Female","N/A","CAT scan tech","Against death penalty","None stated","Probably excused",0],
  [51,"Female","Guilty but can stay open","Software engineer","Against death penalty","Lived near former FBI head Rick DesLauriers","Probably excused",0],
  [54,"Male","N/A","Data management for  Pharmaceutical company","Against but open","None stated","Possibly kept",0],
  [57,"Female","No Determination","Banker","Against death penalty","None stated","Probably excused",0],
  [58,"Female","N/A","Small business employee","N/A","Destination wedding planned","Claiming hardship",0],
  [59,"Female","Guilty","International company","Supports death penalty","None stated","Probably excused",0],
  [60,"Female","Guilty but can stay open","Manager for Hospital system","Open","Husband retired firefighter","Possibly kept",0],
  [61,"Male","N/A","Rock star","N/A","Band going on tour","Claiming hardship",0],
  [62,"Male","Guilty","Postal Service clerk","Supports death penalty","Wife was at explosions, aided victims","Probably excused",0],
  [63,"Female","N/A","Book keeper","N/A","Financial difficulty","Claiming hardship",0],
  [64,"Female","No Determination","Hospital lab tech","Open","None stated","Possibly kept",0],
  [65,"Female","Guilty but can stay open","Lumber company administrator","Against but open","Brother in law's cousin married to a victim","Possibly kept",0],
  [67,"Female","N/A","Nursing home operator","N/A","Financial difficulty","Claiming hardship",0],
  [69,"Female","No Determination","Hospital billing office","Open","None stated","Possibly kept",0],
  [70,"Female","Guilty","Stay home mom","Against death penalty","None stated","Probably excused",0],
  [71,"Female","N/A","S & R, warehouse","N/A","Financial difficulty","Claiming hardship",0],
  [73,"Male","N/A","Restaurant bus boy","N/A","College student","Claiming hardship",0],
  [74,"Female","No Determination","Teacher","Open","Participated in Boston Strong activities.","Possibly kept",0],
  [75,"Male","Guilty but can stay open","Management consultant","Supports but open","None stated","Possibly kept",0],
  [76,"Male","Guilty but can stay open","Architect","Supports death penalty","Friends at explosions, co-worker's wfie a surgeon who aided victims","Probably excused",0],
  [79,"Male","Guilty","Constructioin industry consult","N/A","Single father, financial difficulty","Claiming hardship",0],
  [83,"Male","Guilty but can stay open","Student","Open","None stated","Possibly kept",0],
  [84,"Female","Guilty","Teacher","Against death penalty","None stated","Probably excused",0],
  [85,"Male","Guilty","Web company","N/A","None stated","Probably excused",0],
  [90,"Female","Guilty","Childre's social worker","NA","Colleagues treted victims","Probably excused",0],
  [92,"Female","No Determination","Exeecutive assistant","Open","Bought a Boston Strong bumper sticker","Possibly kept",0],
  [98,"Male","No Determination","Software engineer","Supports but open","None stated","Possibly kept",0],
  [100,"Male","N/A","Glass construction","N/A","Financial difficulty","Claiming hardship",0],
  [102,"Female","No Determination","Registered nurse","Open","None stated","Possibly kept",0],
  [108,"Female","N/A","N/A","N/A","Cares for disabled daughter","Claiming hardship",0],
  [109,"Female","N/A","Childre's social worker","N/A","Leaving kids would be hardship","Claiming hardship",0],
  [111,"Male","N/A","Architectural draftsman","N/A","Financial difficulty","Claiming hardship",0],
  [113,"Male","Guilty but can stay open","Employee Benefits broker","Against but open","None stated","Possibly kept",0],
  [115,"Male","Guilty","Retired real estate","Open","None stated","Probably excused",0],
  [116,"Female","Guilty","N/A","N/A","Husband Boston firefighter, donated to One Fund","Probably excused",0],
  [118,"Female","Guilty but can stay open","Retired dental hygienest ","Against death penalty","Bought Boston Strong merchandise","Probably excused",0],
  [119,"Female","Guilty but can stay open","Dental assistant","Supports but open","None stated","Possibly kept",0],
  [126,"Male","No Determination","Tanning Salon","Against death penalty","None stated","Probably excused",0],
  [128,"Male","N/A","Retired DPW supervisor","N/A","Close friend Cambridge officer, responded to Collier shooting/Vacation schedulled","Claiming hardship",0],
  [129,"Female","Guilty but can stay open","Federal reserve","Open","Supported One Fund events","Possibly kept",0],
  [132,"Female","Guilty but can stay open","Office Administrator","Supports death penalty","None stated","Probably excused",0],
  [134,"Female","No Determination","Art teacher","Against but open","None stated","Possibly kept",0],
  [138,"Male","No Determination","Local water department","Open","None stated","Possibly kept",0],
  [139,"Male","No Determination","Information Technology","Open","None stated","Possibly kept",0],
  [143,"Male","Guilty but can stay open","Harvard film archives","Against death penalty","Affected by shlter-in-place","Probably excused",0],
  [145,"Female","Guilty but can stay open","Accountant","Open","None stated","Possibly kept",0],
  [152,"Male","No Determination","Recent college grad","Against but open","None stated","Possibly kept",0],
  [156,"Male","No Determination","Software Development","Against but open","Affected by shlter-in-place","Possibly kept",0],
  [158,"Male","Guilty","Transportation safety analyst","N/A","None stated","Probably excused",0],
  [159,"Male","N/A","Lighting tecnology","Supports death penalty","None stated","Probably excused",0],
  [161,"Male","No Determination","Restaurateur","Open","None stated","Possibly kept",0],
  [169,"Male","Guilty","Voiceover engineer","N/A","Wife a nurse at MGH, not involved with patients","Probably excused",0],
  [171,"Female","Guilty","Hospital lab tech","N/A","Financial difficulty","Probably excused",0],
  [172,"Female","Guilty but can stay open","High performance computer work","Supports but open","Worked at Boston University at time of fundraising for Lu Lingzhi ","Possibly kept",0],
  [173,"Female","Guilty but can stay open","Professor/researcher","Against but open","None stated","Possibly kept",0],
  [176,"Male","No Determination","Retired technical drawing teacher/professor","Open","None stated","Possibly kept",0],
  [181,"Male","N/A","Marine engineer","N/a","None stated/sidebar discussion","Probably excused",0],
  [183,"Female","No Determination","Whole Foods manager","Open","None stated","Possibly kept",0],
  [184,"Female","N/A","teacher","N/A","Family travel plans","Probably excused",0],
  [185,"Female","Guilty but can stay open","risks/contracts manager for construction company","Open","Bought Boston Strong merchandise","Possibly kept",0],
  [186,"Female","Guilty","Human resources director","Supports death penalty","Supported One Fund fundraisers","Probably excused",0],
  [189,"Male","N/A","Education-focused non-profit","N/A","Ran Boston Marathon, emotionally attached","Probably excused",0],
  [190,"Female","Guilty but can stay open","Operations manager non-profit care organization","Supports but open","None stated","Possibly kept",0],
  [191,"Male","No Determination","Healthcare coordinator","Open","None stated","Possibly kept",0],
  [195,"Female","No Determination","unemployed","Open","None stated","Possibly kept",0],
  [198,"Male","Guilty","teacher","N/A","None stated","Probably excused",0],
  [199,"Female","No Determination","Registered nurse","Against but open","None stated","Possibly kept",0],
  [204,"Female","No Determination","Medical records office","Open","None stated","Possibly kept",0],
  [205,"Male","No Determination","Engineer","Open","Ran Boston Marathon years ago","Possibly kept",0],
  [208,"Male","Guilty","N/A","N/A","None stated ","Probably excused",0],
  [211,"Female","N/A","special ed teacher","N/A","Expressed nervousness","Probably excused",0],
  [215,"Female","No Determination","Book keeper","Against but open","None stated ","Possibly kept",0],
  [219,"Female","Guilty","Unemployed medical assistant","Against death penalty","None stated ","Probably excused",0],
  [223,"Female","N/A","accountant","N/A","Financial difficulty","Claiming hardship",0],
  [229,"Female","No Determination","Social worker consultant","Open","None stated","Possibly kept",0],
  [243,"Female","Guilty but can stay open","Health information management","Against but open","None stated ","Possibly kept",0],
  [244,"Female","No Determination","Former software engineer/farmer","Against death penalty","Claimed anxiety, followed conspiracy theories","Probably excused",0],
  [245,"Male","Guilty but can stay open","Medical interpreter","Open","None stated  ","Possibly kept",0],
  [246,"Female","No Determination","contracts administrator health insurance","Supports but open","None stated ","Possibly kept",0],
  [250,"Male","Guilty but can stay open","designer beer company","Against death penalty","Company sponsors Bosth Marathon","Probably excused",0],
  [251,"Male","No Determination","makes golf balls","Open","Defense lawyers point out Facebook postings disparaging Muslims","Probably excused",0],
  [255,"Female","N/A","Childre's social worker","N/A","Financial difficulty","Probably excused",0],
  [258,"Female","Guilty but can stay open","Retired school administrator","Against but open","Relatives are police officers. ","Possibly kept",0]
]
;